export const eventTemplateLightColors = {
  bg: '#f8f4ef',
  bgAlt: '#f6f1e8',
  bgCanvas: '#f9f7f2',
  text: '#201b16',
  textStrong: '#2c241b',
  textMuted: '#7a746b',
  textMutedStrong: '#5f5446',
  textSoft: '#8c8478',
  textSubtle: '#b7ab9c',
  textTertiary: '#aca497',
  surface: '#fffdf9',
  surfaceRaised: '#ffffff',
  surfaceSoft: '#fff8f0',
  surfaceHover: '#f6f0e7',
  border: '#eadfce',
  borderSoft: '#efe2d1',
  borderWarm: '#ebdecd',
  borderDashed: '#e4d7c6',
  borderCard: '#eee4d8',
  borderActive: '#dabb95',
  strong: '#1b1712',
  strongForeground: '#fff9f2',
  accent: '#c07d2f',
  accentStrong: '#d69037',
  accentSoft: '#fff5e7',
  accentMuted: '#ad8b61',
  accentGradientFrom: '#f2d8bc',
  accentGradientTo: '#f9ede1',
  success: '#0f7377',
  successSoft: '#e7f4f2',
  secondary: '#8a5a9e',
  secondarySoft: '#f3ecf8',
  rose: '#ba5b76',
  roseSoft: '#fde2ec',
  danger: '#d04f37',
  dangerSoft: '#fbebe6',
  overlay: 'rgba(21, 18, 12, 0.18)',
  toolbar: 'rgba(248, 244, 239, 0.86)',
  toolbarStrong: 'rgba(255,250,243,0.96)',
  toolbarBorder: 'rgba(95, 78, 57, 0.08)',
} as const;

export const eventTemplateDarkColors = {
  bg: '#120f0d',
  bgAlt: '#17120f',
  bgCanvas: '#1d1815',
  text: '#f8f0e7',
  textStrong: '#f8f0e7',
  textMuted: '#b7aa9a',
  textMutedStrong: '#ddd2c5',
  textSoft: '#8c7d6d',
  textSubtle: '#8c7d6d',
  textTertiary: '#b7aa9a',
  surface: '#1d1815',
  surfaceRaised: '#1d1815',
  surfaceSoft: '#2a221d',
  surfaceHover: '#2a221d',
  border: '#3a2f27',
  borderSoft: '#3a2f27',
  borderWarm: '#6e5333',
  borderDashed: '#3a2f27',
  borderCard: '#3a2f27',
  borderActive: '#6e5333',
  strong: '#f8f0e7',
  strongForeground: '#1b1712',
  accent: '#f1b562',
  accentStrong: '#f1b562',
  accentSoft: 'rgba(241,181,98,0.14)',
  accentMuted: '#d9b78d',
  accentGradientFrom: '#6e5333',
  accentGradientTo: '#2a221d',
  success: '#5bc0b6',
  successSoft: 'rgba(91,192,182,0.16)',
  secondary: '#b693d8',
  secondarySoft: 'rgba(182,147,216,0.16)',
  rose: '#e48bac',
  roseSoft: 'rgba(228,139,172,0.16)',
  danger: '#f18a6e',
  dangerSoft: 'rgba(241,138,110,0.16)',
  overlay: 'rgba(0,0,0,0.42)',
  toolbar: 'rgba(29,24,21,0.94)',
  toolbarStrong: 'rgba(29,24,21,0.94)',
  toolbarBorder: 'rgba(248,240,231,0.08)',
} as const;

export function getEventTemplateManageVars(isDark: boolean) {
  const c = isDark ? eventTemplateDarkColors : eventTemplateLightColors;

  return {
    '--manage-bg': c.bg,
    '--manage-fg': c.text,
    '--manage-card': c.surface,
    '--manage-card-border': c.border,
    '--manage-muted': c.textMuted,
    '--manage-muted-strong': c.textMutedStrong,
    '--manage-subtle': c.textSubtle,
    '--manage-hover': c.surfaceHover,
    '--manage-input': isDark ? c.bgAlt : c.surfaceRaised,
    '--manage-btn': c.surfaceHover,
    '--manage-toolbar': isDark ? c.toolbarStrong : eventTemplateLightColors.toolbarStrong,
    '--manage-toolbar-border': c.toolbarBorder,
    '--manage-link-active': c.textStrong,
    '--manage-strong': c.strong,
    '--manage-strong-foreground': c.strongForeground,
    '--manage-accent': c.accent,
    '--manage-accent-soft': c.accentSoft,
    '--manage-accent-border': c.borderWarm,
    '--manage-accent-muted': c.accentMuted,
    '--manage-success': c.success,
    '--manage-success-soft': c.successSoft,
    '--manage-secondary': c.secondary,
    '--manage-secondary-soft': c.secondarySoft,
    '--manage-rose': c.rose,
    '--manage-rose-soft': c.roseSoft,
    '--manage-danger': c.danger,
    '--manage-danger-soft': c.dangerSoft,
  } as const;
}
