// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(hydrogen)/about/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/faq">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/about/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/about/what-happens/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/what-happens">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/about/what-happens/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/alarm-monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alarm-monitoring">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/alarm-monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/api-docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api-docs">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/api-docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/appointment/list/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/appointment/list">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/appointment/list/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/appointment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/appointment">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/appointment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/bidding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bidding">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/bidding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/blank/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blank">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/blank/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/business/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/business">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/business/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/calendars/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendars/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/calendars/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/calendars/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendars/create">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/calendars/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/calendars/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendars">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/calendars/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/connect/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/connect">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/connect/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/create-event/continue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create-event/continue">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/create-event/continue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/create-event/form/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create-event/form">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/create-event/form/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/create-event/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create-event">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/create-event/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crm">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/daily-overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/daily-overview">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/daily-overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/discover/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/discover">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/discover/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/ecommerce/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecommerce/cart">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/ecommerce/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/ecommerce/categories/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecommerce/categories/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/ecommerce/categories/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/ecommerce/categories/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecommerce/categories/create">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/ecommerce/categories/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/ecommerce/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecommerce/categories">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/ecommerce/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/ecommerce/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecommerce/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/ecommerce/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/ecommerce/orders/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecommerce/orders/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/ecommerce/orders/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/ecommerce/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecommerce/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/ecommerce/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/ecommerce/orders/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecommerce/orders/create">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/ecommerce/orders/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/ecommerce/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecommerce/orders">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/ecommerce/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/ecommerce/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecommerce">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/ecommerce/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/ecommerce/products/[slug]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecommerce/products/[slug]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/ecommerce/products/[slug]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/ecommerce/products/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecommerce/products/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/ecommerce/products/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/ecommerce/products/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecommerce/products/create">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/ecommerce/products/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/ecommerce/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecommerce/products">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/ecommerce/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/ecommerce/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecommerce/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/ecommerce/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/ecommerce/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecommerce/shop">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/ecommerce/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/email-templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/email-templates">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/email-templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/event-calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event-calendar">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/event-calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/events/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/events/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/events/browse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/browse">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/events/browse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/executive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/executive">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/executive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/feed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feed">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/feed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/file-manager/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/file-manager">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/file-manager/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/file/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/file">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/file/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/financial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/financial">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/financial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/fleet-overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fleet-overview">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/fleet-overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/forms/newsletter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/newsletter">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/forms/newsletter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/forms/profile-settings/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/profile-settings/billing">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/forms/profile-settings/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/forms/profile-settings/integration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/profile-settings/integration">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/forms/profile-settings/integration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/forms/profile-settings/notification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/profile-settings/notification">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/forms/profile-settings/notification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/forms/profile-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/profile-settings">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/forms/profile-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/forms/profile-settings/password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/profile-settings/password">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/forms/profile-settings/password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/forms/profile-settings/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/profile-settings/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/forms/profile-settings/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/forms/profile-settings/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/profile-settings/team">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/forms/profile-settings/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/invoice/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/invoice/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/invoice/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/invoice/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/invoice/builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/builder">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/invoice/builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/invoice/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/create">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/invoice/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/invoice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/invoice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/job-board/feed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/job-board/feed">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/job-board/feed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/job-board/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/job-board">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/job-board/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/logistics/customer-profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/customer-profile">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/logistics/customer-profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/logistics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/logistics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/logistics/shipments/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/shipments/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/logistics/shipments/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/logistics/shipments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/shipments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/logistics/shipments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/logistics/shipments/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/shipments/create">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/logistics/shipments/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/logistics/shipments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/shipments">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/logistics/shipments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/logistics/tracking/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/tracking/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/logistics/tracking/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/logistics/tracking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/tracking">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/logistics/tracking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/luma/create-event/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/luma/create-event">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/luma/create-event/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/luma/event-detail/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/luma/event-detail">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/luma/event-detail/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/luma/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/luma/events">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/luma/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/luma/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/luma">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/luma/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/machinery/alarms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/machinery/alarms">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/machinery/alarms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/machinery/condition-monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/machinery/condition-monitoring">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/machinery/condition-monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/machinery/system-monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/machinery/system-monitoring">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/machinery/system-monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/manage/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manage/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/manage/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/operation-monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operation-monitoring">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/operation-monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/operation-overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operation-overview">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/operation-overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/podcast/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/podcast">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/podcast/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/point-of-sale/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/point-of-sale">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/point-of-sale/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/project/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/project/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/reports/consumption/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/consumption">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/reports/consumption/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/reports/day/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/day">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/reports/day/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/reports/unified/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/unified">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/reports/unified/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/roles-permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roles-permissions">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/roles-permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/search/flight/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search/flight">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/search/flight/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/search/nft/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search/nft">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/search/nft/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/search/real-estate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search/real-estate">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/search/real-estate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/social-media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/social-media">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/social-media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/store-analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store-analytics">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/store-analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/support/inbox/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support/inbox/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/support/inbox/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/support/inbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support/inbox">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/support/inbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/support/snippets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support/snippets">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/support/snippets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/support/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support/templates">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/support/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/tables/basic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tables/basic">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/tables/basic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/tables/collapsible/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tables/collapsible">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/tables/collapsible/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/tables/dnd/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tables/dnd">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/tables/dnd/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/tables/enhanced/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tables/enhanced">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/tables/enhanced/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/tables/pagination/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tables/pagination">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/tables/pagination/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/tables/pinning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tables/pinning">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/tables/pinning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/tables/resizable/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tables/resizable">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/tables/resizable/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/tables/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tables/search">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/tables/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/tables/sticky-header/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tables/sticky-header">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/tables/sticky-header/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/widgets/cards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/widgets/cards">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/widgets/cards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/widgets/charts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/widgets/charts">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/widgets/charts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/widgets/icons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/widgets/icons">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/widgets/icons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/widgets/maps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/widgets/maps">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/widgets/maps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(other-pages)/access-denied/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access-denied">> = Specific
  const handler = {} as typeof import("../../src/app/(other-pages)/access-denied/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(other-pages)/coming-soon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coming-soon">> = Specific
  const handler = {} as typeof import("../../src/app/(other-pages)/coming-soon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(other-pages)/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance">> = Specific
  const handler = {} as typeof import("../../src/app/(other-pages)/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(other-pages)/not-found/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/not-found">> = Specific
  const handler = {} as typeof import("../../src/app/(other-pages)/not-found/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(other-pages)/welcome/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/welcome">> = Specific
  const handler = {} as typeof import("../../src/app/(other-pages)/welcome/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(forgot-password)/forgot-password-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-password-1">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(forgot-password)/forgot-password-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(forgot-password)/forgot-password-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-password-2">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(forgot-password)/forgot-password-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(forgot-password)/forgot-password-3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-password-3">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(forgot-password)/forgot-password-3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(forgot-password)/forgot-password-4/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-password-4">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(forgot-password)/forgot-password-4/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(forgot-password)/forgot-password-5/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-password-5">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(forgot-password)/forgot-password-5/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(otp)/otp-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/otp-1">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(otp)/otp-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(otp)/otp-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/otp-2">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(otp)/otp-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(otp)/otp-3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/otp-3">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(otp)/otp-3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(otp)/otp-4/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/otp-4">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(otp)/otp-4/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(otp)/otp-5/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/otp-5">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(otp)/otp-5/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(sign-in)/sign-in-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/sign-in-1">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(sign-in)/sign-in-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(sign-in)/sign-in-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/sign-in-2">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(sign-in)/sign-in-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(sign-in)/sign-in-3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/sign-in-3">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(sign-in)/sign-in-3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(sign-in)/sign-in-4/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/sign-in-4">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(sign-in)/sign-in-4/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(sign-in)/sign-in-5/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/sign-in-5">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(sign-in)/sign-in-5/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(sign-up)/sign-up-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/sign-up-1">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(sign-up)/sign-up-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(sign-up)/sign-up-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/sign-up-2">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(sign-up)/sign-up-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(sign-up)/sign-up-3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/sign-up-3">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(sign-up)/sign-up-3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(sign-up)/sign-up-4/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/sign-up-4">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(sign-up)/sign-up-4/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/(sign-up)/sign-up-5/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/sign-up-5">> = Specific
  const handler = {} as typeof import("../../src/app/auth/(sign-up)/sign-up-5/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/multi-step-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/multi-step-2">> = Specific
  const handler = {} as typeof import("../../src/app/multi-step-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/multi-step/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/multi-step">> = Specific
  const handler = {} as typeof import("../../src/app/multi-step/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signin">> = Specific
  const handler = {} as typeof import("../../src/app/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/uploadthing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploadthing">> = Specific
  const handler = {} as typeof import("../../src/app/api/uploadthing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(hydrogen)/ecommerce/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/ecommerce">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/ecommerce/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/forms/profile-settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/forms/profile-settings">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/forms/profile-settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(hydrogen)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(hydrogen)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(other-pages)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(other-pages)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/multi-step-2/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/multi-step-2">> = Specific
  const handler = {} as typeof import("../../src/app/multi-step-2/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/multi-step/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/multi-step">> = Specific
  const handler = {} as typeof import("../../src/app/multi-step/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
